### PR TITLE
Update scripts

### PR DESCRIPTION
**Pull request by sekmiller**
This PR addresses the issue in https://github.com/IQSS/dataverse/issues/6750. It includes a python script (query2json.py) that runs a database query, transforms the results into json and writes the results to a file. It adds Subjects and identifiers to the json. It also modifies the diff item in the json so that it reflects the difference in days from today back to the most recent publishing activity within each dataverse and its sub dataverses as applicable. Instructions for setting up a chron job are also included in UpdateDoc.txt.

### CODE REVIEW

**Comment by sekmiller** [comment]
New version of the sample data is in data.json. It was run against a now seven month old copy of prod so the lowest diff would be in the neighborhood of 215.

**Comment by djbrooke** [comment]
@sekmiller I moved some content to the readme - take a look and feel free to make any edits.

**Review by pdurbin — APPROVED** [review]
I didn't run the code myself but I didn't see anything crazy in it. As long as it works, it should be fine.

**Review by landreev — APPROVED** [review]
I agree, "dvndb" (an installer default) makes more sense in a checked-in script.

**Review by scolapasta — APPROVED** [review]
Change looks good.

**Pull request merged**
